batch_size: 128
checkpoints: ./checkpoints/
clip_grad: 1.0
complex: false
data_path: Lorenz.npy
dataset: l63
decay_weight: 1.0e-05
delta_t: 0.1
devices: 0,1,2,3
div_expert: 100000.0
div_gate: 10000.0
div_main: 10000.0
downsample: 1
dynamic_dim: 6
enc_in: 3
gate_layers: 3
gpu: 0
hidden_dim: 128
hidden_layers: 4
k: 1
loss: hs1d
lr_expert: 0.001
lr_gate: 0.001
lr_main: 0.01
model: LRAN
norm: true
num_complex: null
num_generators: 0
num_workers: 10
omega_dim: null
omega_layers: null
patience: 20
pred_len: 1000
radius: false
rel: true
root_path: ./dataset/Lorenz/
seed: 2025
seq_len: 30
setting: l63_30_LRAN_numg0_lhs1d_lrm0.01_lre0.001_lrg0.001_nTrue_dyna6_h128_hl4_gl3_k1_epo500
stable: true
train_epochs: 500
use_amp: false
use_gpu: true
use_multi_gpu: false
warm_pct: 0.1