batch_size: 128
checkpoints: ./checkpoints/
clip_grad: 1.0
complex: true
data_path: KS_8pi.npy
dataset: KS
decay_weight: 1.0e-05
delta_t: 0.1
devices: 0,1,2,3
div_expert: 100000.0
div_gate: 10000.0
div_main: 10000.0
downsample: 4
dynamic_dim: 32
enc_in: 128
gate_layers: 2
gpu: 0
hidden_dim: 1024
hidden_layers: 4
k: 2
loss: hs
lr_expert: 0.001
lr_gate: 0.001
lr_main: 0.001
model: CocycleNet
norm: true
num_complex: null
num_generators: 60
num_workers: 10
omega_dim: null
omega_layers: null
patience: 100
pred_len: 75
radius: false
rel: true
root_path: ./dataset/KS/
seed: 2025
seq_len: 40
setting: KS_40_CocycleNet_numg60_lhs_lrm0.001_lre0.001_lrg0.001_nTrue_dyna32_h1024_hl4_gl2_k2_epo500
stable: false
train_epochs: 500
use_amp: false
use_gpu: true
use_multi_gpu: false
warm_pct: 0.1