batch_size: 128
checkpoints: ./checkpoints/
clip_grad: 1.0
complex: false
data_path: Pendulum.npy
dataset: pendulum
decay_weight: 1.0e-05
delta_t: 0.1
devices: 0,1,2,3
div_expert: 100000.0
div_gate: 10000.0
div_main: 10000.0
downsample: 5
dynamic_dim: 2
enc_in: 2
gate_layers: 2
gpu: 0
hidden_dim: 64
hidden_layers: 3
k: 2
loss: hs1d
lr_expert: 0.001
lr_gate: 0.001
lr_main: 0.01
model: LRAN
norm: false
num_complex: null
num_generators: 0
num_workers: 10
omega_dim: null
omega_layers: null
patience: 20
pred_len: 200
radius: false
rel: true
root_path: ./dataset/Pendulum/
seed: 2025
seq_len: 30
setting: pendulum_30_LRAN_numg0_lhs1d_lrm0.01_lre0.001_lrg0.001_nFalse_dyna2_h64_hl3_gl2_k2_epo200
stable: false
train_epochs: 200
use_amp: false
use_gpu: true
use_multi_gpu: false
warm_pct: 0.1